### ISSUE TITLE
Support for individual node cost

### ISSUE THREAD

**Issue by magnublo** [marcelo-s/A-Star-Java-Implementation#1]
I like this implementation a lot. It was very easy and slick to put inside my own code.

Would you consider adding support for individual node movement cost? That would make this implementation even better.

**Comment by marcelo-s** [comment]
Thanks for the feedback. 
I know, it is hard to find good and easy to understand implementations of AStar. 
I added a constructor with the movement costs as arguments, so you can use it if you need it.
