### ISSUE TITLE
Performance increase

### ISSUE THREAD

**Issue by GuillaumeBlin** [marcelo-s/A-Star-Java-Implementation#2]
First of all thanks for this implementation. 
I would just suggest you to change the implementation of the closedList to an HashSet which performs lot more efficiently the contain operation. In a bigger graph (say thousand nodes), the performance gap is already visible. 
Best

**Comment by marcelo-s** [comment]
Hi @GuillaumeBlin , thanks for pointing out that improvement, you are totally right. I updated the implementation with a HashSet. And thanks for your words!
